management.endpoints.web.exposure.include=health,info,scheduledtasks
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.endpoint.scheduledtasks.access=READ_ONLY
management.info.git.enabled=true
app.log.file=logs/app.log